services:
  spring_app:
    container_name: gestionCompositeUserAccessCardAPP
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    networks:
      - mynetwork

networks:
  mynetwork:
